server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ayaka520:3306/myredis?useSSL=false&serverTimezone=UTC
    username: myredis
    password: 8AeF3MZrMDkPtDrL
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  redis:
    host: ayaka520
    port: 6379
    password: gangajiang521
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 10ms

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
