---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by GanGaJiang.
--- DateTime: 2022/11/4 15:28
---

-- 参数列表 由外部获取
local voucherId = ARGV[1]
local userId = ARGV[2]

-- 秒杀卷库存的key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单业务的key
local orderKey = 'seckill:order:' .. userId


-- 业务脚本
-- 判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1 -- 返回 1 表示库存不足
end
-- 判断一人一单
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2 -- 返回 2 表示不能重复下单 -- 返回 1 表示库存不足
end
-- 扣减库存
redis.call('incrby', stockKey, -1)
-- 用户下单
redis.call('sadd', orderKey, userId)
return 0 -- 表示有资格下单，订单成功