server:
  port: 9090

spring:
  redis:
    host: ayaka520
    port: 6379
    password: gangajiang521
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 10ms
